// Licensed to Shonkor under the MIT License.

namespace Shonkor.Bench;

/// <summary>
/// What must hold before a run is started or scored (#473). Pure: every fact about the world (HEADs,
/// dirty files, indexed revisions, which key files exist) is handed in by <see cref="Ap6Runner"/>, so the
/// rules are testable without a checkout or a database.
///
/// <para>
/// Class C tokens are a function of the corpus revision (<c>keys-c.sh</c>): a mapping generated at another
/// commit would grade an arm against different names without any error. That is the check the #466 review
/// added to this ticket, and it runs before the first prompt is written.
/// </para>
/// </summary>
internal static class Ap6Preconditions
{
    /// <summary>The world as the runner observed it. <c>null</c> means "not observable" and is reported as such, never assumed fine.</summary>
    /// <param name="BrainHead">HEAD of the repository the class A/B tasks were keyed from.</param>
    /// <param name="BrainIndexedRevision">What the Brain graph says it indexed (<c>IGraphStore.GetIndexedRevisionAsync</c>).</param>
    /// <param name="BrainDirtyCsFiles">Modified or untracked <c>.cs</c> files in the Brain working tree.</param>
    /// <param name="BrainKeyFileExists">Whether a class A/B key file exists under the Brain root.</param>
    /// <param name="CorpusHead">HEAD of the class-C corpus checkout.</param>
    /// <param name="CorpusIndexedRevision">What the corpus graph says it indexed.</param>
    /// <param name="CorpusDirtyFiles">Modified tracked <c>.yml/.cs/.cshtml/.sln</c> files in the corpus working tree.</param>
    public sealed record World(
        string? BrainHead,
        string? BrainIndexedRevision,
        IReadOnlyList<string> BrainDirtyCsFiles,
        Func<string, bool> BrainKeyFileExists,
        string? CorpusHead,
        string? CorpusIndexedRevision,
        IReadOnlyList<string> CorpusDirtyFiles);

    /// <summary>Every reason not to run; empty when the harness may start. Never throws.</summary>
    public static IReadOnlyList<string> Check(IReadOnlyList<Ap6Task> tasks, Ap6Mapping? mapping, World world)
    {
        var problems = new List<string>();
        var classAb = tasks.Where(t => t.Class is "A" or "B").ToList();
        var classC = tasks.Where(t => t.Class == "C").ToList();

        if (classAb.Count > 0)
        {
            if (world.BrainHead is null) problems.Add("Brain: HEAD not readable (not a git checkout?)");
            if (world.BrainIndexedRevision is null) problems.Add("Brain graph: no indexedRevision recorded — index the tree first (shonkor index . --force)");
            else if (world.BrainHead is not null && !string.Equals(world.BrainHead, world.BrainIndexedRevision, StringComparison.Ordinal))
                problems.Add($"Brain graph indexed '{Short(world.BrainIndexedRevision)}' but HEAD is '{Short(world.BrainHead)}' — re-index so both arms and the key describe the same tree");
            if (world.BrainDirtyCsFiles.Count > 0)
                problems.Add($"Brain: {world.BrainDirtyCsFiles.Count} .cs file(s) differ from HEAD ({Sample(world.BrainDirtyCsFiles)}) — the rg arm reads the working tree, the graph read HEAD; commit or stash");
            foreach (var t in classAb)
                foreach (var f in t.Key?.Files ?? [])
                    if (!world.BrainKeyFileExists(f)) problems.Add($"{t.Id}: key file '{f}' does not exist at HEAD");
        }

        if (classC.Count > 0)
        {
            if (mapping is null)
            {
                problems.Add("class C: mapping file not loaded — <corpus>/bench/ap6-mapping.json (generated by keys-c.sh) is required");
                return problems;
            }
            var rev = mapping.CorpusRevision;
            if (string.IsNullOrEmpty(rev)) problems.Add("mapping: corpusRevision missing");
            foreach (var t in classC)
                if (rev is not null && !string.Equals(t.KeySource?.Ref, rev, StringComparison.Ordinal))
                    problems.Add($"{t.Id}: keySource.ref '{Short(t.KeySource?.Ref)}' != mapping.corpusRevision '{Short(rev)}' — the tokens of the corpus and of the mapping are from different revisions; regenerate both with keys-c.sh at one commit");
            if (world.CorpusHead is null) problems.Add("corpus: HEAD not readable");
            else if (rev is not null && !string.Equals(world.CorpusHead, rev, StringComparison.Ordinal))
                problems.Add($"corpus checkout is at '{Short(world.CorpusHead)}' but the mapping is for '{Short(rev)}' — check out the corpus revision");
            if (world.CorpusDirtyFiles.Count > 0)
                problems.Add($"corpus: {world.CorpusDirtyFiles.Count} tracked .yml/.cs/.cshtml/.sln file(s) modified ({Sample(world.CorpusDirtyFiles)}) — stash or commit");
            if (world.CorpusIndexedRevision is null) problems.Add("corpus graph: no indexedRevision recorded — re-index the corpus with verified plugins first (see bench/golden/ap6/README.md)");
            else if (rev is not null && !string.Equals(world.CorpusIndexedRevision, rev, StringComparison.Ordinal))
                problems.Add($"corpus graph indexed '{Short(world.CorpusIndexedRevision)}' but the mapping is for '{Short(rev)}' — re-index the corpus at that revision");

            problems.AddRange(CheckTokens(classC, mapping));
        }
        return problems;
    }

    /// <summary>
    /// Every token a class-C task uses (key files, key symbols, tokens in the query) must have an entry with a
    /// name. A token used as a key <b>symbol</b> must moreover have a <c>name</c> that is unique within its
    /// <c>kind</c> — an answer symbol is read back by name (<see cref="Ap6Anonymiser.ToTokens"/>), so a shared
    /// name could not tell which entry the arm meant (#505). Key files are read back by path, which is unique by
    /// construction; views sharing <c>Index.cshtml</c> are therefore no problem.
    /// </summary>
    public static IReadOnlyList<string> CheckTokens(IReadOnlyList<Ap6Task> classC, Ap6Mapping mapping)
    {
        var problems = new List<string>();
        var entries = mapping.Entries ?? [];
        var checkedForAmbiguity = new HashSet<string>(StringComparer.Ordinal);
        foreach (var t in classC)
        {
            var symbols = t.Key?.Symbols ?? [];
            var used = (t.Key?.Files ?? []).Concat(symbols).Concat(Ap6Anonymiser.TokensIn(t.Query ?? string.Empty));
            foreach (var token in used)
            {
                if (!entries.TryGetValue(token, out var e))
                {
                    problems.Add($"{t.Id}: token '{token}' has no mapping entry");
                    continue;
                }
                if (string.IsNullOrEmpty(e.Name)) problems.Add($"{t.Id}: token '{token}' has no name in the mapping");
                if (!symbols.Contains(token, StringComparer.Ordinal) || !checkedForAmbiguity.Add(token)) continue;
                var sameName = entries.Where(kv => kv.Key != token && kv.Value.Kind == e.Kind && string.Equals(kv.Value.Name, e.Name, StringComparison.Ordinal))
                    .Select(kv => kv.Key).ToList();
                if (sameName.Count > 0)
                    problems.Add($"{t.Id}: key symbol '{token}' ({e.Kind}) shares its name with {Sample(sameName)} — ambiguous within its kind (#505)");
            }
        }
        return problems;
    }

    private static string Short(string? sha) => sha is null ? "?" : sha.Length > 12 ? sha[..12] : sha;
    private static string Sample(IReadOnlyList<string> xs) => string.Join(", ", xs.Take(5)) + (xs.Count > 5 ? ", …" : "");
}
