// Licensed to Shonkor under the MIT License.

extern alias bench;

using System.Text.Json;
using bench::Shonkor.Bench;

namespace Shonkor.Tests;

/// <summary>
/// The AP6 part 1 task corpus (#466): <c>bench/golden/ap6/tasks.json</c> must be scoreable (30 tasks, 10 per
/// class, mechanical keys, no seed in the query) and must not carry customer data (class C is anonymised;
/// the real mapping lives outside the repository).
///
/// <para>
/// Deny-list design: a hybrid. Fixed patterns (corpus folder, absolute project paths, Sitecore item paths,
/// GUIDs) and a structural rule (class C keys are tokens) need no secret. The customer's own words are
/// checked as SHA-256 digests of the lower-cased word, embedded below — the words never appear in this
/// repository, yet every identifier-like word of the whole file, query prose included, is hashed and
/// compared. The hash guards against an accident (a paste, a forgotten anonymisation), not against a
/// dictionary attack; that is the threat this corpus faces. When the out-of-repo mapping file is present,
/// its <c>denyWords</c> must hash to exactly this set, so the two lists cannot drift apart unnoticed.
/// </para>
/// </summary>
public class Ap6CorpusTests
{
    private static readonly string TasksPath = RepoPaths.File("bench", "golden", "ap6", "tasks.json");

    /// <summary>SHA-256 (lower-case hex) of each lower-cased deny word; generated by keys-c.sh into the mapping.</summary>
    private static readonly HashSet<string> DenyWordHashes =
    [
        "f2d758f9e379babc91f1f5062e2d486a70008cccc3c5d47b75f645e588a0ea09",
        "88578022d5b453c268a01f354193e467dbd1a8a0f95b35215ef1e2c96753119c",
        "551f67997ce2e2d23eb16079656e13eb6de0ee29619a102a6208fe566dcf14a7",
    ];

    /// <summary>
    /// The corpus folder name, assembled at run time so that the pre-commit grep for deny words over this
    /// file stays at zero hits — the folder name contains the customer's token.
    /// </summary>
    private static readonly string CorpusFolder = string.Concat("sitecoreM", "uM");

    // ---------- the real corpus ----------

    [Fact]
    public void TheCorpus_Validates_WithThirtyTasks_TenPerClass()
    {
        var tasks = Ap6Corpus.Load(TasksPath);

        Assert.Empty(Ap6Corpus.Validate(tasks));
        Assert.Equal(30, tasks.Count);
        Assert.Equal(10, tasks.Count(t => t.Class == "A"));
        Assert.Equal(10, tasks.Count(t => t.Class == "B"));
        Assert.Equal(10, tasks.Count(t => t.Class == "C"));
        Assert.Equal(30, tasks.Select(t => t.Id).Distinct().Count());
        Assert.All(tasks, t => Assert.Equal(1, t.SchemaVersion));
    }

    [Fact]
    public void TheCorpus_CarriesNoCustomerData()
    {
        var leaks = Ap6Corpus.FindLeaks(File.ReadAllText(TasksPath), DenyWordHashes);

        Assert.Empty(leaks);
    }

    [Fact]
    public void TheCorpus_ClassAB_KeysAreMergeCommits_ClassC_KeysAreUnicornYml()
    {
        var tasks = Ap6Corpus.Load(TasksPath);

        foreach (var t in tasks.Where(t => t.Class is "A" or "B"))
        {
            Assert.Equal("merge-commit", t.KeySource!.Method);
            Assert.Matches("^[0-9a-f]{7,40}$", t.KeySource.Ref);
            Assert.All(t.Key!.Files!, f => Assert.Matches(@"^(src|plugins|tests)/[^ ]+\.cs$", f));
        }
        foreach (var t in tasks.Where(t => t.Class == "C"))
        {
            Assert.Equal("unicorn-yml", t.KeySource!.Method);
            Assert.All(t.Key!.Files!, f => Assert.Matches(Ap6Corpus.AnonymisedToken, f));
            Assert.All(t.Key!.Symbols!, s => Assert.Matches(Ap6Corpus.AnonymisedToken, s));
        }
    }

    /// <summary>
    /// The two deny-lists must be the same list. Skipped where the corpus is not checked out (CI) — the
    /// hashes above still guard the corpus file there.
    /// </summary>
    [SkippableFact]
    public void TheMappingFile_DenyWords_HashToTheEmbeddedSet()
    {
        var mapping = MappingPath();
        Skip.IfNot(mapping is not null && File.Exists(mapping), "out-of-repo mapping file not present");

        using var doc = JsonDocument.Parse(File.ReadAllText(mapping!));
        var hashes = doc.RootElement.GetProperty("denyWords").EnumerateArray()
            .Select(w => Ap6Corpus.Sha256Hex(w.GetString()!.ToLowerInvariant()))
            .ToHashSet();

        Assert.Equal(DenyWordHashes.Order(), hashes.Order());
    }

    /// <summary><c>&lt;Corpus-A path&gt;/bench/ap6-mapping.json</c>, the corpus root taken from <c>projects.json</c> by name.</summary>
    private static string? MappingPath()
    {
        var projects = RepoPaths.File("projects.json");
        if (!File.Exists(projects)) return null;
        using var doc = JsonDocument.Parse(File.ReadAllText(projects));
        foreach (var p in doc.RootElement.GetProperty("Projects").EnumerateArray())
        {
            if (p.GetProperty("Name").GetString() == "Corpus-A")
                return Path.Combine(p.GetProperty("Path").GetString()!, "bench", "ap6-mapping.json");
        }
        return null;
    }

    // ---------- the validator, on synthetic corpora ----------

    /// <summary>The default query carries the id, so a synthetic corpus has no duplicate query within a class (#490).</summary>
    private static Ap6Task Task(string id, string cls, string? query = null,
        string[]? files = null, string[]? symbols = null, string? method = null, string? @ref = null,
        string? expectation = null, bool seedInKey = false, string? corpus = null)
    {
        query ??= $"Which file declares the thing of {id}?";
        var (defCorpus, defExpectation, defMethod) = cls switch
        {
            "A" => ("Brain", "rg", "merge-commit"),
            "B" => ("Brain", "graph", "merge-commit"),
            _ => ("Corpus-A", "graph-only", "unicorn-yml"),
        };
        return new Ap6Task(1, id, cls, corpus ?? defCorpus, query,
            new Ap6Key((files ?? ["src/X/Foo.cs"]).ToList(), (symbols ?? ["Foo"]).ToList()),
            new Ap6KeySource(method ?? defMethod, @ref ?? (cls == "C" ? "9d7f9ce" : "de44654380032c1766d089d859c7e3c86ac79a74"), "rule"),
            seedInKey, expectation ?? defExpectation);
    }

    private static List<Ap6Task> Thirty() =>
        Enumerable.Range(1, 10).Select(i => Task($"A-{i:00}", "A"))
            .Concat(Enumerable.Range(1, 10).Select(i => Task($"B-{i:00}", "B")))
            .Concat(Enumerable.Range(1, 10).Select(i => Task($"C-{i:00}", "C", files: ["Controller-01"], symbols: ["Controller-01"])))
            .ToList();

    [Fact]
    public void AWellFormedSyntheticCorpus_HasNoProblems()
    {
        Assert.Empty(Ap6Corpus.Validate(Thirty()));
    }

    [Fact]
    public void TwentyNineTasks_IsAProblem()
    {
        var tasks = Thirty(); tasks.RemoveAt(29);

        var problems = Ap6Corpus.Validate(tasks);

        Assert.Contains(problems, p => p.Contains("expected 30 tasks, found 29"));
        Assert.Contains(problems, p => p.Contains("class C: expected 10 tasks, found 9"));
    }

    [Fact]
    public void ElevenOfOneClass_IsAProblem()
    {
        var tasks = Thirty(); tasks[29] = Task("A-11", "A");

        var problems = Ap6Corpus.Validate(tasks);

        Assert.Contains(problems, p => p.Contains("class A: expected 10 tasks, found 11"));
    }

    [Fact]
    public void DuplicateIds_AreAProblem()
    {
        var tasks = Thirty(); tasks[1] = Task("A-01", "A");

        Assert.Contains(Ap6Corpus.Validate(tasks), p => p.Contains("duplicate id 'A-01'"));
    }

    [Fact]
    public void DuplicateQueriesWithinAClass_AreAProblem_AcrossClassesNot()
    {
        const string q = "Which other files and types must change together with `GraphIndexScanner` when its contract changes?";
        var tasks = Thirty();
        tasks[10] = Task("B-01", "B", q);
        tasks[12] = Task("B-03", "B", q);
        tasks[0] = Task("A-01", "A", q);

        var problems = Ap6Corpus.Validate(tasks);

        Assert.Single(problems, p => p.Contains("duplicate query"));
        Assert.Contains(problems, p => p.Contains("class B: duplicate query shared by B-01, B-03"));
    }

    [Fact]
    public void AMissingRequiredField_IsAProblem_NotAnException()
    {
        var tasks = Ap6Corpus.Parse("""[{ "schemaVersion": 1, "id": "A-01", "class": "A" }]""");

        var problems = Ap6Corpus.Validate(tasks);

        Assert.Contains(problems, p => p.Contains("A-01: missing query"));
        Assert.Contains(problems, p => p.Contains("A-01: missing key"));
        Assert.Contains(problems, p => p.Contains("A-01: missing keySource"));
        Assert.Contains(problems, p => p.Contains("A-01: missing corpus"));
        Assert.Contains(problems, p => p.Contains("A-01: missing expectation"));
    }

    [Fact]
    public void AClassOutsideABC_IsAProblem()
    {
        var tasks = Thirty(); tasks[0] = Task("A-01", "D");

        Assert.Contains(Ap6Corpus.Validate(tasks), p => p.Contains("class must be A, B or C, was 'D'"));
    }

    [Theory]
    [InlineData("A", "unicorn-yml")]
    [InlineData("B", "unicorn-yml")]
    [InlineData("C", "merge-commit")]
    public void TheKeySourceMethod_MustMatchTheClass(string cls, string wrongMethod)
    {
        var problems = Ap6Corpus.Validate([Task("X-01", cls, method: wrongMethod)]);

        Assert.Contains(problems, p => p.Contains($"class {cls} must use keySource.method"));
    }

    [Theory]
    [InlineData("A", "graph")]
    [InlineData("B", "graph-only")]
    [InlineData("C", "rg")]
    public void TheExpectation_MustMatchTheClass(string cls, string wrongExpectation)
    {
        var problems = Ap6Corpus.Validate([Task("X-01", cls, expectation: wrongExpectation)]);

        Assert.Contains(problems, p => p.Contains($"class {cls} must expect"));
    }

    [Fact]
    public void TheCorpusName_MustMatchTheClass()
    {
        var problems = Ap6Corpus.Validate([Task("C-01", "C", corpus: "Brain")]);

        Assert.Contains(problems, p => p.Contains("class C must use corpus 'Corpus-A'"));
    }

    [Fact]
    public void AnEmptyFilesOrSymbolsList_IsAProblem()
    {
        var problems = Ap6Corpus.Validate([Task("A-01", "A", files: [], symbols: [])]);

        Assert.Contains(problems, p => p.Contains("key.files is empty"));
        Assert.Contains(problems, p => p.Contains("key.symbols is empty"));
    }

    [Theory]
    [InlineData("not-a-sha")]
    [InlineData("abc12")]                                       // too short
    [InlineData("DE44654380032C1766D089D859C7E3C86AC79A74")]    // upper-case is not what git prints
    public void AClassABRef_MustBeACommitSha(string badRef)
    {
        Assert.Contains(Ap6Corpus.Validate([Task("A-01", "A", @ref: badRef)]), p => p.Contains("keySource.ref must be a 7-40 hex commit sha"));
        Assert.DoesNotContain(Ap6Corpus.Validate([Task("A-01", "A", @ref: "de44654")]), p => p.Contains("keySource.ref"));
    }

    // ---------- seed-in-key ----------

    [Theory]
    [InlineData("Which file and type declare `Foo`?")]               // the key symbol
    [InlineData("Which file and type declare `Compute`?")]           // a member of a key symbol
    [InlineData("What must change together with Bar?")]              // a key file stem
    public void AQueryThatNamesAKeyMember_IsAProblem_UnlessFlagged(string query)
    {
        var unflagged = Task("B-01", "B", query, files: ["src/X/Bar.cs"], symbols: ["Foo", "Foo.Compute"]);
        var flagged = Task("B-01", "B", query, files: ["src/X/Bar.cs"], symbols: ["Foo", "Foo.Compute"], seedInKey: true);

        Assert.Contains(Ap6Corpus.Validate([unflagged]), p => p.Contains("but seedInKey is false"));
        Assert.DoesNotContain(Ap6Corpus.Validate([flagged]), p => p.Contains("seedInKey"));
    }

    [Fact]
    public void TheSeedCheck_IsWholeWord()
    {
        // `FooBar` and `Foo_x` are not `Foo`; `Rendering-071` is not `Rendering-07`.
        var t = Task("B-01", "B", "Which files change with `FooBar` or Foo_x?", symbols: ["Foo"]);
        var c = Task("C-01", "C", "Which class renders `Rendering-071`?", files: ["Rendering-07"], symbols: ["Rendering-07"]);

        Assert.DoesNotContain(Ap6Corpus.Validate([t]), p => p.Contains("seedInKey"));
        Assert.DoesNotContain(Ap6Corpus.Validate([c]), p => p.Contains("seedInKey"));
        Assert.True(Ap6Corpus.ContainsWord("renders `Rendering-07`?", "Rendering-07"));
    }

    // ---------- deny-list ----------

    private const string CleanCorpus = """
        [
          { "schemaVersion": 1, "id": "A-01", "class": "A", "corpus": "Brain",
            "query": "Which file and type declare `Compute`?",
            "key": { "files": ["src/X/Foo.cs"], "symbols": ["Foo"] },
            "keySource": { "method": "merge-commit", "ref": "de44654", "rule": "r" },
            "seedInKey": false, "expectation": "rg" },
          { "schemaVersion": 1, "id": "C-01", "class": "C", "corpus": "Corpus-A",
            "query": "Which C# class and which Razor view render `Rendering-07`?",
            "key": { "files": ["Controller-03", "View-012"], "symbols": ["Controller-03"] },
            "keySource": { "method": "unicorn-yml", "ref": "9d7f9ce", "rule": "r" },
            "seedInKey": false, "expectation": "graph-only" }
        ]
        """;

    /// <summary>A test-only deny word — the mechanism is proven without writing a real customer word here.</summary>
    private static readonly HashSet<string> TestDenyHashes = [Ap6Corpus.Sha256Hex("acmecorp")];

    [Fact]
    public void ACleanCorpus_HasNoLeaks()
    {
        Assert.Empty(Ap6Corpus.FindLeaks(CleanCorpus, TestDenyHashes));
    }

    [Theory]
    [InlineData("\"src/X/Foo.cs\"", "\"C:/Projects/{corpus}/src/x.yml\"", "absolute projects path")]
    [InlineData("\"src/X/Foo.cs\"", "\"C:/Projects/{corpus}/src/x.yml\"", "corpus folder name")]
    [InlineData("\"src/X/Foo.cs\"", "\"C:\\\\Projects\\\\Brain\\\\src\\\\x.cs\"", "absolute projects path")]
    [InlineData("\"src/X/Foo.cs\"", "\"src/{corpus}/x.yml\"", "corpus folder name")]
    [InlineData("\"rule\": \"r\"", "\"rule\": \"item /sitecore/layout/Renderings/X\"", "Sitecore item path")]
    [InlineData("\"rule\": \"r\"", "\"rule\": \"template 00000000-0000-4000-8000-000000000466\"", "GUID")]
    [InlineData("declare `Compute`", "declare `AcmeCorp.Compute`", "deny-listed word")]
    [InlineData("[\"Controller-03\", \"View-012\"]", "[\"Controller-03\", \"src/Feature/X/Views/Index.cshtml\"]", "class C key file")]
    [InlineData("\"symbols\": [\"Controller-03\"]", "\"symbols\": [\"FooController\"]", "class C key symbol")]
    public void AnInjectedLeak_IsFound(string original, string injected, string expectedKind)
    {
        var text = CleanCorpus.Replace(original, injected.Replace("{corpus}", CorpusFolder));
        Assert.NotEqual(CleanCorpus, text);

        var leaks = Ap6Corpus.FindLeaks(text, TestDenyHashes);

        Assert.Contains(leaks, l => l.Contains(expectedKind));
    }

    [Fact]
    public void TheDenyListHashesWords_CaseInsensitively_InQueryProseToo()
    {
        var text = CleanCorpus.Replace("Which C# class", "Which ACMECORP class");

        Assert.Single(Ap6Corpus.FindLeaks(text, TestDenyHashes));
    }
}
